const mongoose = require("mongoose");

const Schema = mongoose.Schema;

// Category Schema
// categoryId is automatically generated by MongoDB as _id
const CategorySchema = Schema({
  categoryName: {
    type: String,
    required: true,
    trim: true,
  },
});

const Category = mongoose.model("Category", CategorySchema);

module.exports = Category;
